name: estapps
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  go_router: ^14.8.1
  intl: ^0.19.0
  shared_preferences: ^2.5.2
  video_player: ^2.9.3
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/test.mp4
